'use strict';

const PDFDocument = require('pdfkit');

/**
 * Convert an array of flat objects into a CSV string with a header row.
 * Values containing commas, quotes, or newlines are escaped per RFC 4180.
 */
function generateCSV(rows) {
  if (!Array.isArray(rows) || rows.length === 0) {
    return '';
  }
  const headers = Object.keys(rows[0]);
  const escape = (value) => {
    if (value === null || value === undefined) return '';
    const str = String(value);
    if (/[",\n\r]/.test(str)) {
      return `"${str.replace(/"/g, '""')}"`;
    }
    return str;
  };
  const lines = [headers.join(',')];
  for (const row of rows) {
    lines.push(headers.map((h) => escape(row[h])).join(','));
  }
  return lines.join('\r\n');
}

/**
 * Stream a PDF report directly to the Express response (no disk write).
 *
 * @param {object} res      Express response (Content-Disposition set by caller)
 * @param {string} title    Report title
 * @param {object} meta     { dateRange, generatedBy, generatedAt }
 * @param {object} summary  { total, active, idle, anomalies }
 * @param {Array}  devices  per-device rows for the data table
 */
function generatePDF(res, title, meta, summary, devices) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  doc.pipe(res);

  // --- Cover section ---
  doc.fillColor('#b91c1c').fontSize(24).text(title, { align: 'left' });
  doc.moveDown(0.5);
  doc.fillColor('#111111').fontSize(11);
  doc.text(`Date Range: ${meta.dateRange}`);
  doc.text(`Generated By: ${meta.generatedBy}`);
  doc.text(`Generated At: ${meta.generatedAt}`);
  doc.moveDown(1);

  drawDivider(doc);

  // --- Fleet summary ---
  doc.moveDown(0.8);
  doc.fillColor('#111111').fontSize(15).text('Fleet Summary', { underline: false });
  doc.moveDown(0.5);
  doc.fontSize(11);
  const summaryRows = [
    ['Total Devices', String(summary.total)],
    ['Active', String(summary.active)],
    ['Idle', String(summary.idle)],
    ['With Anomalies', String(summary.anomalies)]
  ];
  for (const [label, value] of summaryRows) {
    doc.text(`${label}:`, { continued: true }).text(`  ${value}`);
  }
  doc.moveDown(1);

  drawDivider(doc);

  // --- Per-device data table ---
  doc.moveDown(0.8);
  doc.fontSize(15).text('Device Details');
  doc.moveDown(0.5);

  const columns = [
    { key: 'device_id', label: 'ID', width: 70 },
    { key: 'device_name', label: 'Name', width: 95 },
    { key: 'operator_name', label: 'Operator', width: 85 },
    { key: 'status', label: 'Status', width: 60 },
    { key: 'fuel_level', label: 'Fuel (L)', width: 55 },
    { key: 'voltage', label: 'Batt (V)', width: 50 },
    { key: 'anomaly', label: 'Anomaly', width: 60 }
  ];

  const startX = doc.x;
  let y = doc.y;

  // Header row
  doc.fontSize(9).fillColor('#ffffff');
  let x = startX;
  const headerHeight = 18;
  doc.rect(startX, y, columns.reduce((s, c) => s + c.width, 0), headerHeight).fill('#374151');
  doc.fillColor('#ffffff');
  for (const col of columns) {
    doc.text(col.label, x + 3, y + 5, { width: col.width - 6, ellipsis: true });
    x += col.width;
  }
  y += headerHeight;

  // Data rows
  doc.fillColor('#111111');
  for (const d of devices) {
    if (y > doc.page.height - 60) {
      doc.addPage();
      y = doc.y;
    }
    x = startX;
    const rowHeight = 16;
    for (const col of columns) {
      let val = d[col.key];
      if (col.key === 'fuel_level' && val != null) val = Number(val).toFixed(1);
      if (col.key === 'voltage' && val != null) val = Number(val).toFixed(2);
      if (val === null || val === undefined) val = '-';
      doc.fontSize(9).text(String(val), x + 3, y + 4, { width: col.width - 6, ellipsis: true });
      x += col.width;
    }
    y += rowHeight;
    doc.moveTo(startX, y).lineTo(startX + columns.reduce((s, c) => s + c.width, 0), y)
      .strokeColor('#e5e7eb').lineWidth(0.5).stroke();
  }

  if (devices.length === 0) {
    doc.moveDown(1).fillColor('#6b7280').fontSize(11)
      .text('No device data available for the selected range.');
  }

  doc.end();
}

function drawDivider(doc) {
  const y = doc.y;
  doc.moveTo(doc.page.margins.left, y)
    .lineTo(doc.page.width - doc.page.margins.right, y)
    .strokeColor('#d1d5db').lineWidth(1).stroke();
}

module.exports = { generateCSV, generatePDF };
